/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-gradient-to-br',
    'from-white/5',
    'to-white/2',
    'text-white',
    'from-\\[\\#040539\\]',
    'to-\\[\\#0c0a6b\\]',
    'border-\\[\\#00c875\\]',
    'border-\\[\\#ffcb00\\]',
    'border-\\[\\#e2435c\\]',
    'bg-\\[\\#00c875\\]',
    'bg-\\[\\#ffcb00\\]',
    'text-\\[\\#00c875\\]',
    'text-\\[\\#ffcb00\\]',
    'text-\\[\\#e2435c\\]',
    'text-\\[\\#535768\\]',
    'bg-\\[\\#f0f3ff\\]',
    'text-\\[\\#5034ff\\]',
    'bg-\\[\\#6c6cff\\]',
    'bg-\\[\\#5a5ad5\\]',
    'shadow-\\[\\#6c6cff\\]/30',
    'from-\\[\\#00c875\\]',
    'to-\\[\\#5034ff\\]',
    'from-\\[\\#ffcb00\\]',
    'to-\\[\\#e2435c\\]',
    'from-\\[\\#00c875\\]',
    'to-\\[\\#ffcb00\\]',
    'from-\\[\\#e2435c\\]',
    'to-\\[\\#ffcb00\\]',
    'from-\\[\\#6c6cff\\]/10',
    'to-\\[\\#00c875\\]/10',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#6c6cff',
        'primary-dark': '#5a5ad5',
        accent1: '#00c875',
        accent2: '#ffcb00',
        accent3: '#e2435c',
        gray: {
          light: '#f0f3ff',
          dark: '#535768',
        },
      },
    },
  },
  plugins: [],
} 